/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package org.demo.application;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Application launched by SpringBoot starter
 * 
 * @author Telosys
 *
 */
@Component
public class Application {

	private static final Logger logger = LoggerFactory.getLogger(Application.class);
	
    /**
     * Application entry point called by SpringBoot starter
     * 
     * @param args
     */
    public void run(String[] args) {
    	logger.info("Starting application...");
    	logger.debug("Starting application : args.length = {}", args.length);

    }
}
