/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * DTO class for "Attachment"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
public class AttachmentDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private byte[] attachment ;

    /**
     * Constructor
     */
    public AttachmentDTO() {
		super();
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Attachment[");
		sb.append("id=").append(id);
		// attribute 'attachment' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
