/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import java.io.Serializable;

/**
 * DTO class for "Item"
 *
 * @author Telosys
 *
 */
public class ItemDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int cost ;
    private String description ;
    private Integer partnerId ;
    //--- LINKS ( RELATIONSHIPS )
    private PartnerDTO partner ; 

    /**
     * Constructor
     */
    public ItemDTO() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setCost( int cost ) {
        this.cost = cost ;
    }
    public int getCost() {
        return this.cost;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setPartnerId( Integer partnerId ) {
        this.partnerId = partnerId ;
    }
    public Integer getPartnerId() {
        return this.partnerId;
    }

    public PartnerDTO getPartner() {
        return this.partner;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Item[");
		sb.append("id=").append(id);
		sb.append(separator).append("cost=").append(cost);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("partnerId=").append(partnerId);
		sb.append("]");
		return sb.toString();
	}
}
