/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import java.io.Serializable;

/**
 * DTO class for "Partner"
 *
 * @author Telosys
 *
 */
public class PartnerDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String name ;
    private String description ;
    private String website ;

    /**
     * Constructor
     */
    public PartnerDTO() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setWebsite( String website ) {
        this.website = website ;
    }
    public String getWebsite() {
        return this.website;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Partner[");
		sb.append("id=").append(id);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("website=").append(website);
		sb.append("]");
		return sb.toString();
	}
}
