/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import java.io.Serializable;

/**
 * DTO class for "Solution"
 *
 * @author Telosys
 *
 */
public class SolutionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String description ;
    private Integer entityId ;
    private Integer taskId ;
    private Integer creatorId ;
    //--- LINKS ( RELATIONSHIPS )
    private UsersDTO users ; 
    private EntityDTO entity ; 
    private TaskDTO task ; 

    /**
     * Constructor
     */
    public SolutionDTO() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setEntityId( Integer entityId ) {
        this.entityId = entityId ;
    }
    public Integer getEntityId() {
        return this.entityId;
    }

    public void setTaskId( Integer taskId ) {
        this.taskId = taskId ;
    }
    public Integer getTaskId() {
        return this.taskId;
    }

    public void setCreatorId( Integer creatorId ) {
        this.creatorId = creatorId ;
    }
    public Integer getCreatorId() {
        return this.creatorId;
    }

    public UsersDTO getUsers() {
        return this.users;
    } 

    public EntityDTO getEntity() {
        return this.entity;
    } 

    public TaskDTO getTask() {
        return this.task;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Solution[");
		sb.append("id=").append(id);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("entityId=").append(entityId);
		sb.append(separator).append("taskId=").append(taskId);
		sb.append(separator).append("creatorId=").append(creatorId);
		sb.append("]");
		return sb.toString();
	}
}
