/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO class for "Task"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
public class TaskDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String title ;
    private String description ;
    private String taskType ;
    private LocalDate createdAt ;
    private BigDecimal reward ;
    private String tag ;
    private Integer locationId ;
    private Integer entityId ;
    private Integer creatorId ;
    //--- LINKS ( RELATIONSHIPS )
    private UsersDTO users ; 
    private EntityDTO entity ; 
    private LocationDTO location ; 

    /**
     * Constructor
     */
    public TaskDTO() {
		super();
    }
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Task[");
		sb.append("id=").append(id);
		sb.append(separator).append("title=").append(title);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("taskType=").append(taskType);
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append(separator).append("reward=").append(reward);
		sb.append(separator).append("tag=").append(tag);
		sb.append(separator).append("locationId=").append(locationId);
		sb.append(separator).append("entityId=").append(entityId);
		sb.append(separator).append("creatorId=").append(creatorId);
		sb.append("]");
		return sb.toString();
	}
}
