/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO class for "Task"
 *
 * @author Telosys
 *
 */
public class TaskDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String title ;
    private String description ;
    private String taskType ;
    private LocalDate createdAt ;
    private BigDecimal reward ;
    private String tag ;
    private Integer locationId ;
    private Integer entityId ;
    private Integer creatorId ;
    //--- LINKS ( RELATIONSHIPS )
    private UsersDTO users ; 
    private EntityDTO entity ; 
    private LocationDTO location ; 

    /**
     * Constructor
     */
    public TaskDTO() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setTitle( String title ) {
        this.title = title ;
    }
    public String getTitle() {
        return this.title;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setTaskType( String taskType ) {
        this.taskType = taskType ;
    }
    public String getTaskType() {
        return this.taskType;
    }

    public void setCreatedAt( LocalDate createdAt ) {
        this.createdAt = createdAt ;
    }
    public LocalDate getCreatedAt() {
        return this.createdAt;
    }

    public void setReward( BigDecimal reward ) {
        this.reward = reward ;
    }
    public BigDecimal getReward() {
        return this.reward;
    }

    public void setTag( String tag ) {
        this.tag = tag ;
    }
    public String getTag() {
        return this.tag;
    }

    public void setLocationId( Integer locationId ) {
        this.locationId = locationId ;
    }
    public Integer getLocationId() {
        return this.locationId;
    }

    public void setEntityId( Integer entityId ) {
        this.entityId = entityId ;
    }
    public Integer getEntityId() {
        return this.entityId;
    }

    public void setCreatorId( Integer creatorId ) {
        this.creatorId = creatorId ;
    }
    public Integer getCreatorId() {
        return this.creatorId;
    }

    public UsersDTO getUsers() {
        return this.users;
    } 

    public EntityDTO getEntity() {
        return this.entity;
    } 

    public LocationDTO getLocation() {
        return this.location;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Task[");
		sb.append("id=").append(id);
		sb.append(separator).append("title=").append(title);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("taskType=").append(taskType);
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append(separator).append("reward=").append(reward);
		sb.append(separator).append("tag=").append(tag);
		sb.append(separator).append("locationId=").append(locationId);
		sb.append(separator).append("entityId=").append(entityId);
		sb.append(separator).append("creatorId=").append(creatorId);
		sb.append("]");
		return sb.toString();
	}
}
