-- Insert data into the 'entity_attachment' table
-- INSERT INTO entity_attachment (entity_id, attachment_id)
-- VALUES
-- (1, 1),
-- (2, 2),
-- (3, 3);
-- Add more INSERT statements for additional entity_attachment relationships as needed
