/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.persistence.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.UUID;

/**
 * JPA entity class for "Attachment"
 *
 * @author Telosys
 */
@Entity
@Data
@Table(name = "attachment", schema = "public")
public class Attachment implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column(name = "owner_id", nullable = false)
    private UUID owner_id;

    @Lob
    @Column(name = "attachment", nullable = false)
    private byte[] attachment;
}
