/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.persistence.entities;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;

/**
 * JPA entity class for "Entity"
 *
 * @author Telosys
 *
 */
@jakarta.persistence.Entity
@Table(name="entity", schema="public" )
public class Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="entity_type", nullable=false, length=2147483647)
    private String     entityType ;

    /**
     * Constructor
     */
    public Entity() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setEntityType( String entityType ) {
        this.entityType = entityType ;
    }
    public String getEntityType() {
        return this.entityType;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Entity[");
		sb.append("id=").append(id);
		sb.append(separator).append("entityType=").append(entityType);
		sb.append("]");
		return sb.toString();
	}

}
