/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.persistence.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import jakarta.persistence.*;
import jakarta.persistence.Entity;

/**
 * JPA entity class for "FlywaySchemaHistory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="flyway_schema_history", schema="public" )
public class FlywaySchemaHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="installed_rank", nullable=false)
    private int        installedRank ;

    //--- OTHER DATA FIELDS 
    @Column(name="version", length=50)
    private String     version ;

    @Column(name="description", nullable=false, length=200)
    private String     description ;

    @Column(name="type", nullable=false, length=20)
    private String     type ;

    @Column(name="script", nullable=false, length=1000)
    private String     script ;

    @Column(name="checksum")
    private Integer    checksum ;

    @Column(name="installed_by", nullable=false, length=100)
    private String     installedBy ;

    @Column(name="installed_on", nullable=false)
    private LocalDateTime installedOn ;

    @Column(name="execution_time", nullable=false)
    private int        executionTime ;

    @Column(name="success", nullable=false)
    private boolean    success ;

    /**
     * Constructor
     */
    public FlywaySchemaHistory() {
		super();
    }
    
    public void setInstalledRank( int installedRank ) {
        this.installedRank = installedRank ;
    }
    public int getInstalledRank() {
        return this.installedRank;
    }

    public void setVersion( String version ) {
        this.version = version ;
    }
    public String getVersion() {
        return this.version;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    public void setScript( String script ) {
        this.script = script ;
    }
    public String getScript() {
        return this.script;
    }

    public void setChecksum( Integer checksum ) {
        this.checksum = checksum ;
    }
    public Integer getChecksum() {
        return this.checksum;
    }

    public void setInstalledBy( String installedBy ) {
        this.installedBy = installedBy ;
    }
    public String getInstalledBy() {
        return this.installedBy;
    }

    public void setInstalledOn( LocalDateTime installedOn ) {
        this.installedOn = installedOn ;
    }
    public LocalDateTime getInstalledOn() {
        return this.installedOn;
    }

    public void setExecutionTime( int executionTime ) {
        this.executionTime = executionTime ;
    }
    public int getExecutionTime() {
        return this.executionTime;
    }

    public void setSuccess( boolean success ) {
        this.success = success ;
    }
    public boolean isSuccess() {
        return this.success;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("FlywaySchemaHistory[");
		sb.append("installedRank=").append(installedRank);
		sb.append(separator).append("version=").append(version);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("type=").append(type);
		sb.append(separator).append("script=").append(script);
		sb.append(separator).append("checksum=").append(checksum);
		sb.append(separator).append("installedBy=").append(installedBy);
		sb.append(separator).append("installedOn=").append(installedOn);
		sb.append(separator).append("executionTime=").append(executionTime);
		sb.append(separator).append("success=").append(success);
		sb.append("]");
		return sb.toString();
	}

}
