/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.persistence.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.UUID;

/**
 * JPA entity class for "Item"
 *
 * @author Telosys
 */
@Data
@Entity
@Table(name = "item", schema = "public")
public class Item implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    //--- OTHER DATA FIELDS 
    @Column(name = "cost", nullable = false)
    private int cost;

    @Column(name = "description", nullable = false, length = 100)
    private String description;


    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name = "partner_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Partner partner;

}
