/*
 * Created on 2023-10-21 ( 17:17:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.diospyros.uplift.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import jakarta.persistence.Entity;

/**
 * JPA entity class for "Location"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="location", schema="public" )
public class Location implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="decimal_degrees", nullable=false, length=2147483647)
    private String     decimalDegrees ;

    /**
     * Constructor
     */
    public Location() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setDecimalDegrees( String decimalDegrees ) {
        this.decimalDegrees = decimalDegrees ;
    }
    public String getDecimalDegrees() {
        return this.decimalDegrees;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Location[");
		sb.append("id=").append(id);
		sb.append(separator).append("decimalDegrees=").append(decimalDegrees);
		sb.append("]");
		return sb.toString();
	}

}
